import type { Metadata } from "next";
import { FaArrowLeft } from "react-icons/fa6";
import Link from "next/link";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const minecraftBold = localFont({
  src: "../fonts/MinecraftBold-nMK1.otf",
  variable: "--font-minecraft-bold",
  display: "swap",
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${minecraftBold.variable} ${montserrat.variable} antialiased`}
      >
        <Link
          href="https://www.evopixel.xyz/"
          className="fixed top-6 left-6 z-50 bg-black/50 text-white font-semibold py-2 px-4 rounded-lg flex items-center gap-2 hover:bg-black/70 transition"
        >
          <FaArrowLeft size={16} />
          <span>Back</span>
        </Link>

        {children}
      </body>

    </html>
  );
}
